// TODO generated by agent, need review

import { ContainerType, IntKind, MapType, metainfo, PropInfo, Register, SetType, TypeValue } from "../meta/mod.ts";

export interface IIntVld {
    kind?: IntKind;
    min?: number | bigint;
    max?: number | bigint;
    enum?: Record<number, string>;
}

export interface IStringVld {
    size?: [number | undefined, number | undefined];
    enum?: Record<number | string, string | number>;
    pattern?: RegExp;
}

export interface IContainerVld {
    size?: [number | undefined, number | undefined];
    mapele?: IVld;
}

export interface IVld {
    nullable?: boolean;
    vld?: (val: unknown) => Error | null;
    int?: IIntVld;
    string?: IStringVld;
    container?: IContainerVld;
}

export const reg = new Register<{}, IVld, {}>(Symbol("vld"));

export function vld(ele: unknown): Error | null {
    if (typeof ele !== "object") return new Error("not object");
    if (ele == null) return new Error("null");
    const cls = (ele as object).constructor;
    if (typeof cls !== "function") return null;
    const props = metainfo(reg, cls).props({ readable: true });
    if (!props) return null;
    const impl = mkvld(cls, props);
    return impl(ele);
}

const vldcache = new WeakMap<object, (ele: unknown) => Error | null>();

function mkvld(cls: object, props: ReadonlyMap<string, PropInfo<IVld>>): (ele: unknown) => Error | null {
    const cached = vldcache.get(cls);
    if (cached) return cached;

    const impl: (ele: unknown) => Error | null = (ele) => {
        if (typeof ele !== "object") return new Error("not object");
        if (ele == null) return new Error("null");

        for (const [key, prop] of props) {
            const pv = Object.getOwnPropertyDescriptor(ele, key);
            const val = pv == null ? null : pv.get ? pv.get.call(ele) : pv.value;
            if (val == null) {
                if (prop?.opts?.nullable) continue;
                return new Error(`missing required field, ${key}`);
            }
            const err = vldval(val, prop.designtype, prop.opts);
            if (err) return new Error(`${key}: ${err.message}`);
        }
        return null;
    };

    vldcache.set(cls, impl);
    return impl;
}

function vldval(val: unknown, type: TypeValue | undefined, opts: IVld | undefined): Error | null {
    if (!opts) return null;

    if (opts.vld) {
        const err = opts.vld(val);
        if (err) return err;
    }

    if (type instanceof ContainerType) {
        return opts.container ? vldcontainer(val, type, opts.container) : null;
    }

    switch (type) {
        case Number:
            {
                if (opts.int) return vldint(val, opts.int);
                return typeof val === "number" ? null : new Error("not a number");
            }
        case String:
            {
                if (opts.string) return vldstr(val, opts.string);
                return typeof val === "string" ? null : new Error("not a string");
            }
        case Boolean:
            {
                return typeof val === "boolean" ? null : new Error("not a boolean");
            }
        default:
            {
                if (typeof type === "function") return vld(val);
                return null;
            }
    }
}

const IntRanges: Record<Exclude<IntKind, "bigint">, [bigint, bigint]> = {
    int16: [-32768n, 32767n],
    int32: [-2147483648n, 2147483647n],
    int64: [-9223372036854775808n, 9223372036854775807n],
    uint16: [0n, 65535n],
    uint32: [0n, 4294967295n],
    uint64: [0n, 18446744073709551615n],
};

function vldint(val: unknown, opts: IIntVld): Error | null {
    const { kind, min, max, enum: enumset } = opts;

    let bv: bigint;
    if (typeof val === "bigint") {
        bv = val;
    } else if (typeof val === "number" && Number.isInteger(val)) {
        bv = BigInt(val);
    } else {
        return new Error("not an integer");
    }

    if (kind) {
        if (kind === "bigint") {
            if (typeof val !== "bigint") return new Error(`expect bigint, got ${typeof val}`);
        } else {
            const r = IntRanges[kind];
            if (bv < r[0] || bv > r[1]) return new Error(`${kind} out of range: ${bv}`);
        }
    }

    if (min != null) {
        const m = typeof min === "bigint" ? min : BigInt(min);
        if (bv < m) return new Error(`value ${bv} less than min ${min}`);
    }
    if (max != null) {
        const m = typeof max === "bigint" ? max : BigInt(max);
        if (bv > m) return new Error(`value ${bv} greater than max ${max}`);
    }

    if (enumset) {
        if (!(String(val) in enumset)) return new Error(`value ${val} not in enum`);
    }

    return null;
}

function vldstr(val: unknown, opts: IStringVld): Error | null {
    if (typeof val !== "string") return new Error("not a string");

    const { size, enum: enumset, pattern } = opts;

    if (size) {
        const [min, max] = size;
        const len = val.length;
        if (min != null && len < min) return new Error(`length ${len} less than min ${min}`);
        if (max != null && len > max) return new Error(`length ${len} greater than max ${max}`);
    }

    if (enumset && !(val in enumset)) return new Error("value not in enum");

    if (pattern && !pattern.test(val)) return new Error(`value not match pattern ${pattern}`);

    return null;
}

function vldcontainer(val: unknown, type: ContainerType, opts: IContainerVld): Error | null {
    let len: number;
    let elems: Iterable<unknown>;

    if (type instanceof MapType) {
        if (!(val instanceof Map)) return new Error("not a map");
        len = val.size;
        elems = val.values();
    } else if (type instanceof SetType) {
        if (!(val instanceof Set)) return new Error("not a set");
        len = val.size;
        elems = val;
    } else {
        if (!Array.isArray(val)) return new Error("not an array");
        len = val.length;
        elems = val;
    }

    if (opts.size) {
        const [min, max] = opts.size;
        if (min != null && len < min) return new Error(`size ${len} less than min ${min}`);
        if (max != null && len > max) return new Error(`size ${len} greater than max ${max}`);
    }

    if (opts.mapele) {
        const eletype = type.eletype;
        for (const e of elems) {
            if (e == null) {
                if (opts.mapele.nullable) continue;
                return new Error("element null but not nullable");
            }
            const err = vldval(e, eletype, opts.mapele);
            if (err) return err;
        }
    }

    return null;
}

export type VldSchema = { [k: string]: unknown };

function toSafeNum(v: number | bigint | undefined): number | undefined {
    if (v == null) return undefined;
    const n = typeof v === "bigint" ? Number(v) : v;
    if (Number.isFinite(n) && Math.abs(n) <= Number.MAX_SAFE_INTEGER) return n;
    return undefined;
}

export function schema(target: unknown): VldSchema {
    let cls: Function;
    if (typeof target === "function") {
        cls = target;
    } else if (typeof target === "object" && target !== null) {
        cls = (target as object).constructor;
    } else {
        throw new Error("schema: expected a class or instance");
    }
    return buildObj(cls, new Set<object>());
}

function buildObj(cls: Function, seen: Set<object>): VldSchema {
    if (typeof cls !== "function") return {};
    if (seen.has(cls)) {
        return { $ref: "#", $comment: `circular reference to ${cls.name || "anonymous"}` };
    }
    seen.add(cls);

    const props = metainfo(reg, cls).props({ readable: true });
    if (!props) {
        return { type: "object" };
    }

    const properties: Record<string, VldSchema> = {};
    const required: string[] = [];
    for (const [key, prop] of props) {
        properties[key] = buildVld(prop.designtype, prop.opts, seen);
        if (!prop.opts?.nullable) required.push(key);
    }

    seen.delete(cls);

    const result: VldSchema = { type: "object", properties };
    if (required.length) result.required = required;
    return result;
}

function buildVld(type: TypeValue | undefined, opts: IVld | undefined, seen: Set<object>): VldSchema {
    const base = buildType(type, opts, seen);
    return opts?.nullable ? withNullable(base) : base;
}

function withNullable(sch: VldSchema): VldSchema {
    if (sch.type != null) {
        const t = Array.isArray(sch.type) ? sch.type : [sch.type as string];
        if (!t.includes("null")) return { ...sch, type: [...t, "null"] };
        return sch;
    }
    return { anyOf: [sch, { type: "null" }] };
}

function buildType(type: TypeValue | undefined, opts: IVld | undefined, seen: Set<object>): VldSchema {
    if (type instanceof ContainerType) {
        return buildContainer(type, opts?.container, seen);
    }
    switch (type) {
        case Number:
            return opts?.int ? buildInt(opts.int) : { type: "number" };
        case String:
            return opts?.string ? buildStr(opts.string) : { type: "string" };
        case Boolean:
            return { type: "boolean" };
        default:
            if (typeof type === "function") return buildObj(type, seen);
            return {};
    }
}

function buildInt(opts: IIntVld): VldSchema {
    const sch: VldSchema = { type: "integer" };
    let lo: number | undefined;
    let hi: number | undefined;

    if (opts.kind) {
        if (opts.kind === "bigint") {
            sch.$comment = "bigint";
        } else {
            const r = IntRanges[opts.kind];
            const klo = toSafeNum(r[0]);
            const khi = toSafeNum(r[1]);
            if (klo != null) lo = klo;
            if (khi != null) hi = khi;
            if (lo == null && hi == null) sch.$comment = opts.kind;
        }
    }

    const olo = toSafeNum(opts.min);
    const ohi = toSafeNum(opts.max);
    if (olo != null) lo = lo == null ? olo : Math.max(lo, olo);
    if (ohi != null) hi = hi == null ? ohi : Math.min(hi, ohi);

    if (lo != null) sch.minimum = lo;
    if (hi != null) sch.maximum = hi;
    if (opts.enum) {
        sch.enum = Object.keys(opts.enum).map((k) => {
            const n = Number(k);
            return Number.isFinite(n) ? n : k;
        });
    }
    return sch;
}

function buildStr(opts: IStringVld): VldSchema {
    const sch: VldSchema = { type: "string" };
    if (opts.size) {
        const [min, max] = opts.size;
        if (min != null) sch.minLength = min;
        if (max != null) sch.maxLength = max;
    }
    if (opts.enum) sch.enum = Object.keys(opts.enum);
    if (opts.pattern) sch.pattern = opts.pattern.source;
    return sch;
}

function buildContainer(type: ContainerType, opts: IContainerVld | undefined, seen: Set<object>): VldSchema {
    const sch: VldSchema = {};
    const itemSch = buildVld(type.eletype, opts?.mapele, seen);

    if (type instanceof MapType) {
        sch.type = "object";
        sch.additionalProperties = itemSch;
        if (opts?.size) {
            const [min, max] = opts.size;
            if (min != null) sch.minProperties = min;
            if (max != null) sch.maxProperties = max;
        }
        return sch;
    }

    sch.type = "array";
    if (type instanceof SetType) sch.uniqueItems = true;
    sch.items = itemSch;
    if (opts?.size) {
        const [min, max] = opts.size;
        if (min != null) sch.minItems = min;
        if (max != null) sch.maxItems = max;
    }
    return sch;
}
